"""Object-store and upload-through-store tests (ws-b storage + db).

Local round trip, key validation, ``object_refs`` helpers, the storage
route, and proof that the upload API stores keys without writing under
``data/uploads`` or ``data/pages``. The GCS round trip runs only when
``DMEF_GCS_BUCKET`` is configured.
"""

from __future__ import annotations

import io
import os
from pathlib import Path
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient

import database.db as db
import routes.upload as upload_route
from main import app
from services.storage import GcsObjectStore, LocalObjectStore, get_store
from services.storage.refs import get_ref, list_refs, record_ref


def _use_tmp_env(tmp_path, monkeypatch):  # type: ignore[no-untyped-def]
    monkeypatch.setattr(db, "DATABASE_PATH", tmp_path / "dmef.db")
    monkeypatch.setenv("DMEF_LOCAL_STORE_DIR", str(tmp_path / "store"))
    monkeypatch.setenv("DMEF_JOB_WORK_DIR", str(tmp_path / "jobs"))
    monkeypatch.delenv("DMEF_STORAGE_BACKEND", raising=False)
    return tmp_path


_PG_IDENTITY_PK = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

# Minimal upload-path schema for PostgreSQL runs. On SQLite the endpoint's
# own init_db() creates the full schema; on Postgres init_db() only verifies
# connectivity (schema comes from alembic, owned by ws-i), so tests ensure
# the tables they touch. All statements are IF NOT EXISTS and dialect-safe.
_PG_SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS object_refs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_table TEXT NOT NULL,
        owner_id TEXT NOT NULL,
        purpose TEXT NOT NULL,
        storage_key TEXT NOT NULL UNIQUE,
        content_type TEXT,
        size_bytes INTEGER,
        created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_object_refs_owner ON object_refs(owner_table, owner_id)",
    f"""
    CREATE TABLE IF NOT EXISTS applications (
        {_PG_IDENTITY_PK},
        loan_id TEXT NOT NULL,
        applicant_name TEXT,
        coapplicant_name TEXT,
        product_type TEXT,
        branch TEXT,
        status TEXT NOT NULL DEFAULT 'uploaded',
        llm_summary TEXT,
        created_at TEXT,
        updated_at TEXT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS uploaded_files (
        {_PG_IDENTITY_PK},
        application_id INTEGER,
        file_path TEXT,
        original_filename TEXT,
        file_size_kb DOUBLE PRECISION,
        total_pages INTEGER,
        digital_pages INTEGER,
        scanned_pages INTEGER,
        uploaded_at TEXT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS audit_log (
        {_PG_IDENTITY_PK},
        application_id INTEGER,
        action TEXT NOT NULL,
        details TEXT,
        timestamp TEXT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS pipeline_progress (
        {_PG_IDENTITY_PK},
        application_id INTEGER NOT NULL UNIQUE,
        stage TEXT NOT NULL DEFAULT 'queued',
        total_pages INTEGER NOT NULL DEFAULT 0,
        digital_pages INTEGER NOT NULL DEFAULT 0,
        scanned_pages INTEGER NOT NULL DEFAULT 0,
        processed_pages INTEGER NOT NULL DEFAULT 0,
        current_page INTEGER,
        percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'processing',
        message TEXT,
        error TEXT,
        started_at TEXT,
        updated_at TEXT,
        completed_at TEXT
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS pipeline_jobs (
        {_PG_IDENTITY_PK},
        application_id INTEGER NOT NULL,
        job_type TEXT NOT NULL DEFAULT 'pdf_pipeline',
        status TEXT NOT NULL DEFAULT 'queued',
        control_state TEXT NOT NULL DEFAULT 'running',
        attempt INTEGER NOT NULL DEFAULT 1,
        parent_job_id INTEGER,
        heartbeat_at TEXT,
        control_requested_at TEXT,
        last_completed_page INTEGER NOT NULL DEFAULT 0,
        error TEXT,
        created_at TEXT NOT NULL,
        started_at TEXT,
        completed_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pipeline_job_inputs (
        job_id INTEGER PRIMARY KEY,
        application_id INTEGER NOT NULL,
        encrypted_payload TEXT NOT NULL,
        source_sha256 TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    f"""
    CREATE TABLE IF NOT EXISTS pipeline_page_events (
        {_PG_IDENTITY_PK},
        application_id INTEGER NOT NULL,
        page_number INTEGER NOT NULL,
        total_pages INTEGER NOT NULL DEFAULT 0,
        page_type TEXT,
        document_type TEXT,
        status TEXT NOT NULL DEFAULT 'completed',
        elapsed_seconds DOUBLE PRECISION,
        error TEXT,
        extracted_fields TEXT,
        completed_at TEXT,
        UNIQUE(application_id, page_number)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS system_settings (
        config_key TEXT PRIMARY KEY,
        config_value TEXT NOT NULL,
        value_type TEXT NOT NULL DEFAULT 'str',
        category TEXT NOT NULL DEFAULT 'general',
        label TEXT,
        description TEXT,
        updated_at TEXT
    )
    """,
]


def _ensure_schema() -> None:
    """Create required tables: full init on SQLite, minimal probe on Postgres."""
    from database.db import dialect

    if dialect() == "postgresql":
        with db.get_connection() as connection:
            for statement in _PG_SCHEMA_STATEMENTS:
                connection.execute(statement)
    else:
        db.init_db()


def test_local_round_trip(tmp_path, monkeypatch) -> None:
    _use_tmp_env(tmp_path, monkeypatch)
    store = LocalObjectStore()
    key = "applications/12/source/a.pdf"
    assert store.put(key, b"hello", "application/pdf") == key
    assert store.get(key) == b"hello"
    assert store.exists(key)
    with store.open(key) as handle:
        assert handle.read() == b"hello"
    assert store.signed_url(key) == f"/storage/{key}"
    assert key in store.list("applications/12/")

    stream_key = "jobs/1/chunk.bin"
    assert store.put(stream_key, io.BytesIO(b"streamed"), "application/octet-stream")
    assert store.get(stream_key) == b"streamed"

    store.delete(key)
    assert not store.exists(key)
    store.delete(key)  # deleting a missing key is a no-op
    assert isinstance(get_store(), LocalObjectStore)


def test_key_validation_rejects_escape_and_absolute_keys(tmp_path, monkeypatch) -> None:
    _use_tmp_env(tmp_path, monkeypatch)
    store = LocalObjectStore()
    for bad_key in ("", "/absolute/key", "../escape", "a/../b", "a/.."):
        with pytest.raises(ValueError):
            store.put(bad_key, b"x", "text/plain")
        with pytest.raises(ValueError):
            store.get(bad_key)
    with pytest.raises(ValueError):
        store.signed_url("/absolute/key")
    with pytest.raises(ValueError):
        store.list("../escape")


def test_object_ref_helpers_record_and_list(tmp_path, monkeypatch) -> None:
    _use_tmp_env(tmp_path, monkeypatch)
    _ensure_schema()

    record_ref(
        "applications", 7, "source", "applications/7/source/a.pdf",
        content_type="application/pdf", size_bytes=5,
    )
    record_ref(
        "applications", 7, "ocr_export", "applications/7/ocr-export.json",
        content_type="application/json", size_bytes=9,
    )
    # Re-recording the same key refreshes its metadata instead of duplicating.
    record_ref(
        "applications", 7, "source", "applications/7/source/a.pdf",
        content_type="application/pdf", size_bytes=6,
    )

    source = get_ref("applications", 7, "source")
    assert source is not None
    assert source["storage_key"] == "applications/7/source/a.pdf"
    assert source["size_bytes"] == 6
    assert source["content_type"] == "application/pdf"

    refs = list_refs("applications", 7)
    assert [ref["purpose"] for ref in refs] == ["source", "ocr_export"]
    assert get_ref("applications", 7, "missing") is None
    assert list_refs("applications", 8) == []


def _create_pdf(path: Path) -> None:
    import fitz

    doc = fitz.open()
    page = doc.new_page()
    page.insert_text(
        (72, 72), "Applicant Name: Ramesh Kumar\nPAN: ABCDE1234F\nLoan Amount: 500000"
    )
    doc.save(path)
    doc.close()


def _snapshot_tree(root: Path) -> set[str]:
    if not root.is_dir():
        return set()
    return {path.relative_to(root).as_posix() for path in root.rglob("*") if path.is_file()}


def test_upload_route_stores_key_and_writes_no_local_files(tmp_path, monkeypatch, auth_headers) -> None:
    _use_tmp_env(tmp_path, monkeypatch)
    _ensure_schema()
    monkeypatch.setattr(upload_route, "UPLOAD_DIR", tmp_path / "uploads")
    monkeypatch.setattr(
        upload_route, "run_pipeline", lambda *_args, **_kwargs: {"pipeline_status": "completed"}
    )
    monkeypatch.setattr(upload_route, "submit_job", lambda fn, *args, **kwargs: fn(*args, **kwargs))

    uploads_root = Path("data/uploads")
    pages_root = Path("data/pages")
    before_uploads = _snapshot_tree(uploads_root)
    before_pages = _snapshot_tree(pages_root)

    pdf_path = tmp_path / "upload.pdf"
    _create_pdf(pdf_path)
    pdf_bytes = pdf_path.read_bytes()
    client = TestClient(app)
    response = client.post(
        "/upload",
        headers=auth_headers,
        data={
            "loan_id": "WSB-STORE-001",
            "applicant_name": "Ramesh Kumar",
            "coapplicant_name": "",
            "product_type": "LAP",
            "branch": "Delhi",
        },
        files={"file": ("upload.pdf", pdf_bytes, "application/pdf")},
    )

    assert response.status_code == 200
    application_id = response.json()["application_id"]

    ref = get_ref("applications", application_id, "source")
    assert ref is not None
    assert ref["storage_key"].startswith(f"applications/{application_id}/source/")
    assert get_store().get(str(ref["storage_key"])) == pdf_bytes

    with db.get_connection() as connection:
        uploaded = connection.execute(
            "SELECT file_path, original_filename FROM uploaded_files WHERE application_id = ?",
            (application_id,),
        ).fetchone()
    assert uploaded is not None
    assert uploaded["file_path"] is None
    assert uploaded["original_filename"] == "upload.pdf"

    # Nothing landed under the legacy trees, and job scratch was cleaned up.
    assert _snapshot_tree(uploads_root) == before_uploads
    assert _snapshot_tree(pages_root) == before_pages
    assert list((tmp_path / "jobs").rglob("*")) == []


def test_storage_route_serves_local_object(tmp_path, monkeypatch, auth_headers) -> None:
    _use_tmp_env(tmp_path, monkeypatch)
    store = LocalObjectStore()
    store.put("applications/9/source/doc.pdf", b"%PDF-stub", "application/pdf")
    client = TestClient(app)

    served = client.get("/storage/applications/9/source/doc.pdf", headers=auth_headers)
    assert served.status_code == 200
    assert served.content == b"%PDF-stub"

    # Traversal attempts never serve objects (client-normalized or rejected).
    assert client.get("/storage/../escape.pdf", headers=auth_headers).status_code in {400, 404}
    assert (
        client.get("/storage/applications/9/source/missing.pdf", headers=auth_headers).status_code
        == 404
    )

    from fastapi import HTTPException

    from routes.storage import serve_stored_object

    with pytest.raises(HTTPException) as exc_info:
        serve_stored_object("../escape.pdf")
    assert exc_info.value.status_code == 400


def test_worker_reload_from_store_after_workdir_deleted(tmp_path, monkeypatch) -> None:
    """Worker+store reload: deleted upload work dir still yields a real PDF.

    Persist inputs for a temp file, delete the file (API ``finally`` cleanup),
    then ``load_job_input`` must re-stage the durable store bytes into
    ``DMEF_JOB_WORK_DIR`` before the checksum. The staged file must match the
    stored bytes.
    """
    import hashlib
    import shutil

    _use_tmp_env(tmp_path, monkeypatch)
    monkeypatch.setenv("DMEF_JOB_INPUT_KEY_FILE", str(tmp_path / "recovery.key"))
    monkeypatch.setenv("DMEF_INLINE_WORKER", "0")
    _ensure_schema()

    from database.db import get_connection
    from services.job_control import load_job_input
    from services.job_runner import enqueue
    from services.pipeline.input_preparation import resolve_job_source

    pdf_path = tmp_path / "source.pdf"
    _create_pdf(pdf_path)
    pdf_bytes = pdf_path.read_bytes()
    expected_sha = hashlib.sha256(pdf_bytes).hexdigest()

    with get_connection() as connection:
        application_id = int(
            connection.execute(
                "INSERT INTO applications (loan_id, status) VALUES ('STORE-RELOAD-001', 'processing')"
                " RETURNING id"
            ).fetchone()["id"]
        )
    # Durable bytes live in the store before enqueue (single /upload layout).
    store_key = f"applications/{application_id}/source/source.pdf"
    get_store().put(store_key, pdf_bytes, "application/pdf")
    record_ref(
        "applications",
        application_id,
        "source",
        store_key,
        content_type="application/pdf",
        size_bytes=len(pdf_bytes),
    )

    # Enqueue hashes the temp file, then the API deletes the work dir.
    staging = tmp_path / "jobs" / "upload-scratch" / "source.pdf"
    staging.parent.mkdir(parents=True, exist_ok=True)
    staging.write_bytes(pdf_bytes)
    job_id = enqueue(
        "pdf_pipeline",
        application_id,
        {"source_path": str(staging), "system_data": {}, "product_type": "LAP"},
    )
    shutil.rmtree(tmp_path / "jobs", ignore_errors=True)
    (tmp_path / "jobs").mkdir(parents=True, exist_ok=True)
    assert not staging.exists()

    payload = load_job_input(application_id, job_id)
    restored = Path(str(payload["source_path"]))
    assert restored.is_file()
    assert hashlib.sha256(restored.read_bytes()).hexdigest() == expected_sha
    assert get_store().get(store_key) == pdf_bytes

    # Explicit resolve prefers the store and never falls back to the deleted hint.
    resolved = resolve_job_source(application_id, str(staging), job_id)
    assert Path(resolved).is_file()
    assert Path(resolved).read_bytes() == pdf_bytes


@pytest.mark.skipif(
    not os.environ.get("DMEF_GCS_BUCKET"),
    reason="GCS integration needs DMEF_GCS_BUCKET",
)
def test_gcs_roundtrip() -> None:
    """Live GCS round trip with Application Default Credentials."""
    store = GcsObjectStore()
    key = f"wsb-tests/{uuid4().hex}/roundtrip.bin"
    try:
        assert store.put(key, b"gcs-hello", "application/octet-stream") == key
        assert store.exists(key)
        assert store.get(key) == b"gcs-hello"
        with store.open(key) as handle:
            assert handle.read() == b"gcs-hello"
        assert key in store.list("wsb-tests/")
        assert store.signed_url(key, expires_seconds=60).startswith("https://")
    finally:
        store.delete(key)
    assert not store.exists(key)
