"""Dialect-aware wrapper tests (ws-b storage + db).

Covers ``?`` translation (including ``?`` inside string literals),
``INSERT ... RETURNING id``, rollback on exception, row access
(``row["col"]``, ``dict(row)``, ``row.keys()``, ``row[0]``), ``executemany``,
``rowcount``/``lastrowid``, and ``dialect()``. Table DDL is valid on both
SQLite and PostgreSQL so the same file runs against docker-compose Postgres.
"""

from __future__ import annotations

import pytest

import database.db as db_module
from database.db import dialect, get_connection


def _use_tmp_db(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(db_module, "DATABASE_PATH", tmp_path / "wrapper.db")


def _make_probe(monkeypatch, table: str) -> None:
    if dialect() == "postgresql":
        ddl = (
            f"CREATE TABLE {table} ("
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "name TEXT, note TEXT)"
        )
    else:
        ddl = f"CREATE TABLE {table} (id INTEGER PRIMARY KEY, name TEXT, note TEXT)"
    with get_connection() as connection:
        connection.execute(f"DROP TABLE IF EXISTS {table}")
        connection.execute(ddl)


def _drop_probe(table: str) -> None:
    with get_connection() as connection:
        connection.execute(f"DROP TABLE IF EXISTS {table}")


def test_placeholder_translation_skips_string_literals(tmp_path, monkeypatch) -> None:
    """A ``?`` inside quotes stays literal; real placeholders still bind."""
    _use_tmp_db(tmp_path, monkeypatch)
    with get_connection() as connection:
        row = connection.execute(
            "SELECT ? AS value, 'is this a ? placeholder' AS literal, "
            "'it''s a ? test' AS escaped",
            (7,),
        ).fetchone()
    assert row is not None
    assert row["value"] == 7
    assert row["literal"] == "is this a ? placeholder"
    assert row["escaped"] == "it's a ? test"
    assert row[0] == 7
    assert set(row.keys()) == {"value", "literal", "escaped"}
    assert dict(row) == {
        "value": 7,
        "literal": "is this a ? placeholder",
        "escaped": "it's a ? test",
    }


def test_placeholder_count_mismatch_raises(tmp_path, monkeypatch) -> None:
    _use_tmp_db(tmp_path, monkeypatch)
    with get_connection() as connection:
        with pytest.raises(ValueError, match="placeholder"):
            connection.execute("SELECT ? AS a, ? AS b", (1,))


def test_insert_returning_id_and_row_access(tmp_path, monkeypatch) -> None:
    """``INSERT ... RETURNING id`` plus cursor/row access on both dialects."""
    _use_tmp_db(tmp_path, monkeypatch)
    table = "wsb_probe_returning"
    _make_probe(monkeypatch, table)
    try:
        with get_connection() as connection:
            row = connection.execute(
                f"INSERT INTO {table} (name, note) VALUES (?, ?) RETURNING id",
                ("alpha", "first"),
            ).fetchone()
            assert row is not None
            new_id = row["id"]
            assert isinstance(new_id, int)
            assert dict(row) == {"id": new_id}

            fetched = connection.execute(
                f"SELECT id, name, note FROM {table} WHERE id = ?", (new_id,)
            ).fetchone()
            assert fetched is not None
            assert fetched["name"] == "alpha"
            assert fetched[0] == new_id
            assert list(fetched.keys()) == ["id", "name", "note"]
    finally:
        _drop_probe(table)


def test_rollback_on_exception_discards_writes(tmp_path, monkeypatch) -> None:
    _use_tmp_db(tmp_path, monkeypatch)
    table = "wsb_probe_rollback"
    _make_probe(monkeypatch, table)
    try:
        with pytest.raises(RuntimeError, match="abort"):
            with get_connection() as failed:
                failed.execute(f"INSERT INTO {table} (name) VALUES (?)", ("gone",))
                raise RuntimeError("abort")
        with get_connection() as connection:
            count = connection.execute(f"SELECT COUNT(*) AS n FROM {table}").fetchone()
            assert count is not None
            assert count["n"] == 0
            assert dict(count)["n"] == 0
    finally:
        _drop_probe(table)


def test_executemany_inserts_all_rows(tmp_path, monkeypatch) -> None:
    _use_tmp_db(tmp_path, monkeypatch)
    table = "wsb_probe_many"
    _make_probe(monkeypatch, table)
    try:
        with get_connection() as connection:
            cursor = connection.executemany(
                f"INSERT INTO {table} (name, note) VALUES (?, ?)",
                [("a", "1"), ("b", "2"), ("c", "3")],
            )
            assert cursor.rowcount == 3
            # A list of tuples is also accepted by .execute().
            cursor = connection.execute(
                f"INSERT INTO {table} (name, note) VALUES (?, ?)",
                [("d", "4"), ("e", "5")],
            )
            assert cursor.rowcount == 2
            rows = connection.execute(
                f"SELECT name FROM {table} ORDER BY name"
            ).fetchall()
            assert [row["name"] for row in rows] == ["a", "b", "c", "d", "e"]
    finally:
        _drop_probe(table)


def test_rowcount_and_lastrowid(tmp_path, monkeypatch) -> None:
    _use_tmp_db(tmp_path, monkeypatch)
    table = "wsb_probe_rowcount"
    _make_probe(monkeypatch, table)
    try:
        with get_connection() as connection:
            if dialect() == "postgresql":
                # No lastrowid on Postgres without RETURNING — the reason the
                # codebase standard is INSERT ... RETURNING id (contracts §1).
                cursor = connection.execute(
                    f"INSERT INTO {table} (name) VALUES (?)", ("solo",)
                )
                assert cursor.lastrowid is None
                created = connection.execute(
                    f"INSERT INTO {table} (name) VALUES (?) RETURNING id", ("duo",)
                ).fetchone()
                assert created is not None and isinstance(created["id"], int)
            else:
                cursor = connection.execute(
                    f"INSERT INTO {table} (name) VALUES (?)", ("solo",)
                )
                assert isinstance(cursor.lastrowid, int)
            updated = connection.execute(
                f"UPDATE {table} SET note = ? WHERE name = ?", ("n", "solo")
            )
            assert updated.rowcount == 1
            missed = connection.execute(
                f"UPDATE {table} SET note = ? WHERE name = ?", ("n", "missing")
            )
            assert missed.rowcount == 0
    finally:
        _drop_probe(table)


def test_dialect_follows_database_url(monkeypatch) -> None:
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert dialect() == "sqlite"
    monkeypatch.setenv("DATABASE_URL", "postgresql://dmef:dmef@localhost:5432/dmef")
    assert dialect() == "postgresql"
