"""Baseline schema for PostgreSQL (ws-i postgres cutover).

Translates the final SQLite ``SCHEMA_STATEMENTS`` in
``database/models.py`` plus all registered schema modules
(``database/llm_calls.py``, ``database/storage_schema.py``) into one
migration using ``op.execute()`` with PostgreSQL DDL.

Translation rules (contracts §1, models.py dialect notes):
- ``INTEGER PRIMARY KEY AUTOINCREMENT`` → ``BIGINT GENERATED BY DEFAULT
  AS IDENTITY PRIMARY KEY``; bare ``INTEGER PRIMARY KEY`` rowid tables
  (``llm_calls``, ``object_refs``) get the same identity PK, except
  ``pipeline_job_inputs.job_id`` which is an explicit FK PK.
- ``BOOLEAN DEFAULT 0`` → ``BOOLEAN DEFAULT FALSE``.
- ``REAL`` → ``DOUBLE PRECISION``.
- ``TIMESTAMP`` → ``TIMESTAMPTZ`` (defaults stay ``CURRENT_TIMESTAMP``).
- ``TEXT`` payload/timestamp columns stay ``TEXT`` — the code compares
  them as strings and stores ``json.dumps`` / ISO-8601 text; consistency
  with the code beats purity.
- Every index from ``INDEX_STATEMENTS`` plus registered-module indexes
  is included.

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-09-05
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS applications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            loan_id TEXT NOT NULL,
            applicant_name TEXT,
            coapplicant_name TEXT,
            product_type TEXT,
            branch TEXT,
            status TEXT NOT NULL DEFAULT 'uploaded',
            llm_summary TEXT,
            ops_summary_en TEXT,
            ops_summary_hi TEXT,
            ops_findings_json TEXT,
            archived_at TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS uploaded_files (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            file_path TEXT,
            original_filename TEXT,
            file_size_kb DOUBLE PRECISION,
            total_pages INTEGER,
            digital_pages INTEGER,
            scanned_pages INTEGER,
            uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS intake_packages (
            package_id TEXT PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            source_filename TEXT NOT NULL,
            source_zip_path TEXT NOT NULL,
            normalized_pdf_path TEXT NOT NULL,
            total_files INTEGER NOT NULL,
            total_pages INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'prepared',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            verified_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS intake_documents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            package_id TEXT NOT NULL REFERENCES intake_packages(package_id),
            source_document_id TEXT NOT NULL,
            original_filename TEXT NOT NULL,
            file_type TEXT NOT NULL,
            source_size_bytes INTEGER NOT NULL,
            page_count INTEGER NOT NULL,
            internal_page_start INTEGER NOT NULL,
            internal_page_end INTEGER NOT NULL,
            UNIQUE(package_id, source_document_id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ground_truth (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            applicant_name TEXT,
            pan_number TEXT,
            loan_amount TEXT,
            phone TEXT,
            address TEXT,
            product_type TEXT,
            raw_json TEXT,
            extracted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            page_number INTEGER,
            page_type TEXT CHECK(page_type IN ('digital', 'scanned')),
            is_readable BOOLEAN,
            ocr_text TEXT,
            ocr_confidence DOUBLE PRECISION,
            ocr_route TEXT CHECK(ocr_route IN ('fast', 'structured', 'google_vision')),
            ocr_escalated BOOLEAN NOT NULL DEFAULT FALSE,
            ocr_processing_time_ms INTEGER NOT NULL DEFAULT 0,
            document_type TEXT,
            classification_confidence DOUBLE PRECISION,
            detection_method TEXT DEFAULT 'detected',
            detected_page_number INTEGER,
            extracted_fields TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS validation_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            rule_id TEXT,
            s_no INTEGER,
            severity TEXT,
            document_type TEXT,
            expected_value TEXT,
            found_value TEXT,
            page_number INTEGER,
            reason TEXT,
            status TEXT DEFAULT 'open',
            evidence_json TEXT,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS reviewer_decisions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            decision TEXT,
            reviewer_note TEXT NOT NULL,
            decided_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pages_meta (
            application_id INTEGER NOT NULL REFERENCES applications(id),
            page_number INTEGER NOT NULL,
            meta_json TEXT,
            PRIMARY KEY (application_id, page_number)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            action TEXT NOT NULL,
            details TEXT,
            timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pipeline_progress (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
            stage TEXT NOT NULL DEFAULT 'queued',
            total_pages INTEGER NOT NULL DEFAULT 0,
            digital_pages INTEGER NOT NULL DEFAULT 0,
            scanned_pages INTEGER NOT NULL DEFAULT 0,
            processed_pages INTEGER NOT NULL DEFAULT 0,
            current_page INTEGER,
            percentage DOUBLE PRECISION NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'processing',
            message TEXT,
            error TEXT,
            started_at TEXT,
            updated_at TEXT,
            completed_at TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pipeline_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL REFERENCES applications(id),
            job_type TEXT NOT NULL DEFAULT 'pdf_pipeline',
            status TEXT NOT NULL DEFAULT 'queued',
            control_state TEXT NOT NULL DEFAULT 'running',
            attempt INTEGER NOT NULL DEFAULT 1,
            max_attempts INTEGER NOT NULL DEFAULT 3,
            next_run_at TEXT,
            failure_reason TEXT,
            batch_id TEXT,
            parent_job_id INTEGER REFERENCES pipeline_jobs(id),
            heartbeat_at TEXT,
            control_requested_at TEXT,
            last_completed_page INTEGER NOT NULL DEFAULT 0,
            error TEXT,
            created_at TEXT NOT NULL,
            started_at TEXT,
            completed_at TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pipeline_job_inputs (
            job_id BIGINT PRIMARY KEY REFERENCES pipeline_jobs(id) ON DELETE CASCADE,
            application_id INTEGER NOT NULL REFERENCES applications(id),
            encrypted_payload TEXT NOT NULL,
            source_sha256 TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS pipeline_page_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL REFERENCES applications(id),
            page_number INTEGER NOT NULL,
            total_pages INTEGER NOT NULL DEFAULT 0,
            page_type TEXT,
            document_type TEXT,
            status TEXT NOT NULL DEFAULT 'completed',
            elapsed_seconds DOUBLE PRECISION,
            error TEXT,
            completed_at TEXT NOT NULL,
            UNIQUE(application_id, page_number)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS classification_review_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL REFERENCES applications(id),
            page_number INTEGER NOT NULL,
            predicted_type TEXT,
            confidence DOUBLE PRECISION,
            reason TEXT NOT NULL,
            anchor_match_results TEXT,
            llm_document_type TEXT,
            created_at TEXT NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ocr_route_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id TEXT NOT NULL,
            document_type TEXT,
            page_number INTEGER NOT NULL,
            event_type TEXT NOT NULL CHECK(event_type IN ('processing', 'escalation')),
            requested_route TEXT NOT NULL CHECK(requested_route IN ('fast', 'structured', 'google_vision')),
            route_used TEXT NOT NULL CHECK(route_used IN ('fast', 'structured', 'google_vision')),
            reason TEXT,
            original_confidence DOUBLE PRECISION,
            duration_ms INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS document_verification_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
            report_json TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS reviewer_summaries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
            summary_json TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS system_settings (
            config_key TEXT PRIMARY KEY,
            config_value TEXT NOT NULL,
            value_type TEXT NOT NULL DEFAULT 'str',
            category TEXT NOT NULL DEFAULT 'general',
            label TEXT,
            description TEXT,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    # Registered schema modules (contracts §3): llm_calls (ws-a) and
    # object_refs (ws-b). Created after the core tables they reference.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS llm_calls (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            application_id INTEGER REFERENCES applications(id),
            provider TEXT,
            model TEXT,
            purpose TEXT,
            tokens_in INTEGER,
            tokens_out INTEGER,
            duration_ms INTEGER,
            est_cost_usd DOUBLE PRECISION,
            created_at TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS object_refs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_table TEXT NOT NULL,
            owner_id TEXT NOT NULL,
            purpose TEXT NOT NULL,
            storage_key TEXT NOT NULL UNIQUE,
            content_type TEXT,
            size_bytes INTEGER,
            created_at TEXT NOT NULL
        )
        """
    )
    # Every index from INDEX_STATEMENTS plus registered-module indexes.
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_uploaded_files_application_id "
        "ON uploaded_files(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_intake_packages_application_id "
        "ON intake_packages(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_intake_documents_package_id "
        "ON intake_documents(package_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ground_truth_application_id "
        "ON ground_truth(application_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_pages_application_id ON pages(application_id)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pages_application_page "
        "ON pages(application_id, page_number)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pages_meta_application_page "
        "ON pages_meta(application_id, page_number)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_validation_results_application_id "
        "ON validation_results(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications(created_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reviewer_decisions_application_id "
        "ON reviewer_decisions(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reviewer_decisions_decided_at "
        "ON reviewer_decisions(decided_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_log_application_id ON audit_log(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_progress_application_id "
        "ON pipeline_progress(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_application_id "
        "ON pipeline_jobs(application_id)"
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status ON pipeline_jobs(status)")
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status_next_run "
        "ON pipeline_jobs(status, next_run_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_application_attempt "
        "ON pipeline_jobs(application_id, attempt)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_job_inputs_application_id "
        "ON pipeline_job_inputs(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_page_events_application_id "
        "ON pipeline_page_events(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pipeline_page_events_application_page "
        "ON pipeline_page_events(application_id, page_number)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_classification_review_log_application_id "
        "ON classification_review_log(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ocr_route_events_document_id "
        "ON ocr_route_events(document_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ocr_route_events_route_used "
        "ON ocr_route_events(route_used)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_document_verification_reports_application_id "
        "ON document_verification_reports(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_reviewer_summaries_application_id "
        "ON reviewer_summaries(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_llm_calls_application_id "
        "ON llm_calls(application_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_object_refs_owner "
        "ON object_refs(owner_table, owner_id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS object_refs CASCADE")
    op.execute("DROP TABLE IF EXISTS llm_calls CASCADE")
    op.execute("DROP TABLE IF EXISTS system_settings CASCADE")
    op.execute("DROP TABLE IF EXISTS reviewer_summaries CASCADE")
    op.execute("DROP TABLE IF EXISTS document_verification_reports CASCADE")
    op.execute("DROP TABLE IF EXISTS ocr_route_events CASCADE")
    op.execute("DROP TABLE IF EXISTS classification_review_log CASCADE")
    op.execute("DROP TABLE IF EXISTS pipeline_page_events CASCADE")
    op.execute("DROP TABLE IF EXISTS pipeline_job_inputs CASCADE")
    op.execute("DROP TABLE IF EXISTS pipeline_jobs CASCADE")
    op.execute("DROP TABLE IF EXISTS pipeline_progress CASCADE")
    op.execute("DROP TABLE IF EXISTS audit_log CASCADE")
    op.execute("DROP TABLE IF EXISTS pages_meta CASCADE")
    op.execute("DROP TABLE IF EXISTS reviewer_decisions CASCADE")
    op.execute("DROP TABLE IF EXISTS validation_results CASCADE")
    op.execute("DROP TABLE IF EXISTS pages CASCADE")
    op.execute("DROP TABLE IF EXISTS ground_truth CASCADE")
    op.execute("DROP TABLE IF EXISTS intake_documents CASCADE")
    op.execute("DROP TABLE IF EXISTS intake_packages CASCADE")
    op.execute("DROP TABLE IF EXISTS uploaded_files CASCADE")
    op.execute("DROP TABLE IF EXISTS applications CASCADE")
