"""Auth users + passwords (fx-integrate-df, ws-d).

Postgres does not run ``database/db.py:init_db()`` when ``DATABASE_URL`` is
set, so the ``users`` / ``user_passwords`` tables registered by
``database/auth_schema.py`` need a migration. Mirrors the SQLite DDL
(contracts §6); role CHECK, UNIQUE email, boolean ``is_active``.

Revision ID: 0004_auth_users
Revises: 0003_llm_calls_and_indexes (fx-schema; merges before this branch
per docs/agents/FIX_WAVE.md merge order)
Create Date: 2026-09-05
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_auth_users"
down_revision: str | Sequence[str] | None = "0003_llm_calls_and_indexes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email TEXT NOT NULL UNIQUE,
            display_name TEXT NOT NULL,
            role TEXT NOT NULL CHECK (role IN ('admin', 'operations')),
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            created_by BIGINT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_passwords (
            user_id BIGINT PRIMARY KEY,
            password_hash TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_passwords CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
