"""SQLite schema statements and shared data models for DMEF.

Dialect notes (ws-i postgres cutover, contracts §1): this module is the
SQLite DDL source of truth. ``INTEGER PRIMARY KEY AUTOINCREMENT`` here is
SQLite-only; the Postgres baseline in ``alembic/versions/0001_baseline.py``
translates every such PK to ``BIGINT GENERATED BY DEFAULT AS IDENTITY
PRIMARY KEY``. ``BOOLEAN DEFAULT 0`` maps to ``BOOLEAN DEFAULT FALSE``,
``REAL`` maps to ``DOUBLE PRECISION``, ``TEXT`` payload columns stay ``TEXT``
(``json.dumps``), and ``TIMESTAMP DEFAULT CURRENT_TIMESTAMP`` maps to
``TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP``. Columns are frozen; do not change
them here — change the alembic baseline instead.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator


class GravitonRecord(BaseModel):
    """Ground-truth borrower data parsed from Graviton JSON pages in a PDF."""

    model_config = ConfigDict(str_strip_whitespace=True)

    application_id: int
    applicant_name: str
    father_name: str
    date_of_birth: str
    aadhaar_number: str
    pan_number: str
    phone_number: str
    address: str
    pin_code: str
    loan_amount: str
    loan_type: str

    @field_validator("aadhaar_number", mode="before")
    @classmethod
    def validate_aadhaar_number(cls, value: Any) -> str:
        """Normalize and validate Aadhaar numbers as exactly 12 digits."""
        if value in (None, ""):
            raise ValueError("aadhaar_number is required")
        normalized = re.sub(r"\D", "", str(value))
        if not re.fullmatch(r"\d{12}", normalized):
            raise ValueError("aadhaar_number must contain exactly 12 digits")
        return normalized

    @field_validator("pan_number", mode="before")
    @classmethod
    def validate_pan_number(cls, value: Any) -> str:
        """Normalize and validate PAN values using ABCDE1234F format."""
        if value in (None, ""):
            raise ValueError("pan_number is required")
        normalized = str(value).strip().upper()
        if not re.fullmatch(r"[A-Z]{5}[0-9]{4}[A-Z]", normalized):
            raise ValueError("pan_number must match ABCDE1234F format")
        return normalized

    @field_validator("phone_number", mode="before")
    @classmethod
    def validate_phone_number(cls, value: Any) -> str:
        """Normalize and validate phone numbers as exactly 10 digits."""
        if value in (None, ""):
            raise ValueError("phone_number is required")
        normalized = re.sub(r"\D", "", str(value))
        if not re.fullmatch(r"\d{10}", normalized):
            raise ValueError("phone_number must contain exactly 10 digits")
        return normalized

    @field_validator("pin_code", mode="before")
    @classmethod
    def validate_pin_code(cls, value: Any) -> str:
        """Normalize and validate Indian PIN codes as exactly 6 digits."""
        if value in (None, ""):
            raise ValueError("pin_code is required")
        normalized = re.sub(r"\D", "", str(value))
        if not re.fullmatch(r"\d{6}", normalized):
            raise ValueError("pin_code must contain exactly 6 digits")
        return normalized


class FieldVerificationResult(BaseModel):
    """Result of comparing one extracted field against ground-truth data."""

    model_config = ConfigDict(str_strip_whitespace=True)

    field_name: str
    extracted_value: Any = None
    db_value: Any = None
    match: bool
    confidence: float = Field(ge=0.0, le=1.0)
    method: Literal["exact", "fuzzy", "llm"]
    mismatch_reason: str | None = None


class DocumentVerificationReport(BaseModel):
    """Final document verification output for one application."""

    application_id: int
    overall_match: bool
    total_fields_checked: int = Field(ge=0)
    matched_fields: int = Field(ge=0)
    failed_fields: list[str]
    field_results: list[FieldVerificationResult]
    verification_timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    needs_manual_review: bool

    @computed_field
    @property
    def match_percentage(self) -> float:
        """Return matched fields as a percentage of all checked fields."""
        if self.total_fields_checked <= 0:
            return 0.0
        return round((self.matched_fields / self.total_fields_checked) * 100.0, 2)


ChecklistStatus = Literal["verified", "needs_review", "missing", "unknown", "not_applicable"]
ChecklistConfidence = Literal["high", "medium", "low"]
ChecklistExtractionSource = Literal["deterministic", "llm_fallback"]


class ChecklistItem(BaseModel):
    """Reviewer-facing result for one deterministic NDC checklist item."""

    model_config = ConfigDict(str_strip_whitespace=True)

    item_number: int
    document_name: str
    status: ChecklistStatus
    confidence: ChecklistConfidence
    confidence_detail: str
    extracted_fields: dict[str, str | None] = Field(default_factory=dict)
    extraction_source: ChecklistExtractionSource = "deterministic"
    narration: str | None = None
    flagged_reason: str | None = None


class ChecklistSummary(BaseModel):
    """Status counts for the 44-item NDC checklist response."""

    total: int = 44
    verified: int = 0
    needs_review: int = 0
    missing: int = 0
    unknown: int = 0
    not_applicable: int = 0


class ChecklistProcessingMetadata(BaseModel):
    """Timing metadata for checklist output generation and upstream phases."""

    ocr_time_ms: int = Field(default=0, ge=0)
    classification_time_ms: int = Field(default=0, ge=0)
    narration_time_ms: int = Field(default=0, ge=0)


class ChecklistVerificationResponse(BaseModel):
    """Top-level 44-item NDC checklist output for the reviewer UI/API."""

    loan_file_id: str
    summary: ChecklistSummary
    items: list[ChecklistItem]
    processing_metadata: ChecklistProcessingMetadata = Field(
        default_factory=ChecklistProcessingMetadata
    )


SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS applications (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        loan_id TEXT NOT NULL,
        applicant_name TEXT,
        coapplicant_name TEXT,
        product_type TEXT,
        branch TEXT,
        status TEXT NOT NULL DEFAULT 'uploaded',
        llm_summary TEXT,
        ops_summary_en TEXT,
        ops_summary_hi TEXT,
        ops_findings_json TEXT,
        archived_at TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS uploaded_files (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        file_path TEXT,
        original_filename TEXT,
        file_size_kb REAL,
        total_pages INTEGER,
        digital_pages INTEGER,
        scanned_pages INTEGER,
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS intake_packages (
        package_id TEXT PRIMARY KEY,
        application_id INTEGER REFERENCES applications(id),
        source_filename TEXT NOT NULL,
        source_zip_path TEXT NOT NULL,
        normalized_pdf_path TEXT NOT NULL,
        total_files INTEGER NOT NULL,
        total_pages INTEGER NOT NULL,
        status TEXT NOT NULL DEFAULT 'prepared',
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        verified_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS intake_documents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        package_id TEXT NOT NULL REFERENCES intake_packages(package_id),
        source_document_id TEXT NOT NULL,
        original_filename TEXT NOT NULL,
        file_type TEXT NOT NULL,
        source_size_bytes INTEGER NOT NULL,
        page_count INTEGER NOT NULL,
        internal_page_start INTEGER NOT NULL,
        internal_page_end INTEGER NOT NULL,
        UNIQUE(package_id, source_document_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ground_truth (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        applicant_name TEXT,
        pan_number TEXT,
        loan_amount TEXT,
        phone TEXT,
        address TEXT,
        product_type TEXT,
        raw_json TEXT,
        extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pages (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        page_number INTEGER,
        page_type TEXT CHECK(page_type IN ('digital', 'scanned')),
        is_readable BOOLEAN,
        ocr_text TEXT,
        ocr_confidence REAL,
        ocr_route TEXT CHECK(ocr_route IN ('fast', 'structured', 'google_vision')),
        ocr_escalated BOOLEAN NOT NULL DEFAULT 0,
        ocr_processing_time_ms INTEGER NOT NULL DEFAULT 0,
        document_type TEXT,
        classification_confidence REAL,
        detection_method TEXT DEFAULT 'detected',
        detected_page_number INTEGER,
        extracted_fields TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS validation_results (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        rule_id TEXT,
        s_no INTEGER,
        severity TEXT,
        document_type TEXT,
        expected_value TEXT,
        found_value TEXT,
        page_number INTEGER,
        reason TEXT,
        evidence_json TEXT,
        status TEXT DEFAULT 'open',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reviewer_decisions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        decision TEXT,
        reviewer_note TEXT NOT NULL,
        decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pages_meta (
        application_id INTEGER NOT NULL REFERENCES applications(id),
        page_number INTEGER NOT NULL,
        meta_json TEXT,
        PRIMARY KEY (application_id, page_number)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER REFERENCES applications(id),
        action TEXT NOT NULL,
        details TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pipeline_progress (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
        stage TEXT NOT NULL DEFAULT 'queued',
        total_pages INTEGER NOT NULL DEFAULT 0,
        digital_pages INTEGER NOT NULL DEFAULT 0,
        scanned_pages INTEGER NOT NULL DEFAULT 0,
        processed_pages INTEGER NOT NULL DEFAULT 0,
        current_page INTEGER,
        percentage REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'processing',
        message TEXT,
        error TEXT,
        started_at TEXT,
        updated_at TEXT,
        completed_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pipeline_jobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL REFERENCES applications(id),
        job_type TEXT NOT NULL DEFAULT 'pdf_pipeline',
        status TEXT NOT NULL DEFAULT 'queued',
        control_state TEXT NOT NULL DEFAULT 'running',
        attempt INTEGER NOT NULL DEFAULT 1,
        max_attempts INTEGER NOT NULL DEFAULT 3,
        next_run_at TEXT,
        failure_reason TEXT,
        batch_id TEXT,
        parent_job_id INTEGER REFERENCES pipeline_jobs(id),
        heartbeat_at TEXT,
        control_requested_at TEXT,
        last_completed_page INTEGER NOT NULL DEFAULT 0,
        error TEXT,
        created_at TEXT NOT NULL,
        started_at TEXT,
        completed_at TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pipeline_job_inputs (
        job_id INTEGER PRIMARY KEY REFERENCES pipeline_jobs(id) ON DELETE CASCADE,
        application_id INTEGER NOT NULL REFERENCES applications(id),
        encrypted_payload TEXT NOT NULL,
        source_sha256 TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS pipeline_page_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL REFERENCES applications(id),
        page_number INTEGER NOT NULL,
        total_pages INTEGER NOT NULL DEFAULT 0,
        page_type TEXT,
        document_type TEXT,
        status TEXT NOT NULL DEFAULT 'completed',
        elapsed_seconds REAL,
        error TEXT,
        completed_at TEXT NOT NULL,
        UNIQUE(application_id, page_number)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS classification_review_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL REFERENCES applications(id),
        page_number INTEGER NOT NULL,
        predicted_type TEXT,
        confidence REAL,
        reason TEXT NOT NULL,
        anchor_match_results TEXT,
        llm_document_type TEXT,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ocr_route_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        document_id TEXT NOT NULL,
        document_type TEXT,
        page_number INTEGER NOT NULL,
        event_type TEXT NOT NULL CHECK(event_type IN ('processing', 'escalation')),
        requested_route TEXT NOT NULL CHECK(requested_route IN ('fast', 'structured', 'google_vision')),
        route_used TEXT NOT NULL CHECK(route_used IN ('fast', 'structured', 'google_vision')),
        reason TEXT,
        original_confidence REAL,
        duration_ms INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS document_verification_reports (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
        report_json TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reviewer_summaries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id INTEGER NOT NULL UNIQUE REFERENCES applications(id),
        summary_json TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS system_settings (
        config_key TEXT PRIMARY KEY,
        config_value TEXT NOT NULL,
        value_type TEXT NOT NULL DEFAULT 'str',
        category TEXT NOT NULL DEFAULT 'general',
        label TEXT,
        description TEXT,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]

MIGRATION_STATEMENTS = [
    "ALTER TABLE validation_results ADD COLUMN s_no INTEGER",
    "ALTER TABLE validation_results ADD COLUMN evidence_json TEXT",
    "ALTER TABLE applications ADD COLUMN ops_summary_en TEXT",
    "ALTER TABLE applications ADD COLUMN ops_summary_hi TEXT",
    "ALTER TABLE applications ADD COLUMN ops_findings_json TEXT",
    "ALTER TABLE applications ADD COLUMN archived_at TEXT",
    "ALTER TABLE pages ADD COLUMN detection_method TEXT DEFAULT 'detected'",
    "ALTER TABLE pages ADD COLUMN detected_page_number INTEGER",
    "ALTER TABLE pages ADD COLUMN ocr_route TEXT",
    "ALTER TABLE pages ADD COLUMN ocr_escalated BOOLEAN NOT NULL DEFAULT 0",
    "ALTER TABLE pages ADD COLUMN ocr_processing_time_ms INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE pipeline_jobs ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 3",
    "ALTER TABLE pipeline_jobs ADD COLUMN next_run_at TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN failure_reason TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN batch_id TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN control_state TEXT NOT NULL DEFAULT 'running'",
    "ALTER TABLE pipeline_jobs ADD COLUMN attempt INTEGER NOT NULL DEFAULT 1",
    "ALTER TABLE pipeline_jobs ADD COLUMN parent_job_id INTEGER REFERENCES pipeline_jobs(id)",
    "ALTER TABLE pipeline_jobs ADD COLUMN heartbeat_at TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN control_requested_at TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN last_completed_page INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE pipeline_jobs ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 3",
    "ALTER TABLE pipeline_jobs ADD COLUMN next_run_at TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN failure_reason TEXT",
    "ALTER TABLE pipeline_jobs ADD COLUMN batch_id TEXT",
]

INDEX_STATEMENTS = [
    "CREATE INDEX IF NOT EXISTS idx_uploaded_files_application_id ON uploaded_files(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_intake_packages_application_id ON intake_packages(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_intake_documents_package_id ON intake_documents(package_id)",
    "CREATE INDEX IF NOT EXISTS idx_ground_truth_application_id ON ground_truth(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pages_application_id ON pages(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pages_application_page ON pages(application_id, page_number)",
    "CREATE INDEX IF NOT EXISTS idx_pages_meta_application_page ON pages_meta(application_id, page_number)",
    "CREATE INDEX IF NOT EXISTS idx_validation_results_application_id ON validation_results(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_applications_created_at ON applications(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_reviewer_decisions_application_id ON reviewer_decisions(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviewer_decisions_decided_at ON reviewer_decisions(decided_at)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_application_id ON audit_log(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_progress_application_id ON pipeline_progress(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_application_id ON pipeline_jobs(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status ON pipeline_jobs(status)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status_next_run ON pipeline_jobs(status, next_run_at)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_application_attempt ON pipeline_jobs(application_id, attempt)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_batch_id ON pipeline_jobs(batch_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_job_inputs_application_id ON pipeline_job_inputs(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_page_events_application_id ON pipeline_page_events(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_pipeline_page_events_application_page ON pipeline_page_events(application_id, page_number)",
    "CREATE INDEX IF NOT EXISTS idx_classification_review_log_application_id ON classification_review_log(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_ocr_route_events_document_id ON ocr_route_events(document_id)",
    "CREATE INDEX IF NOT EXISTS idx_ocr_route_events_route_used ON ocr_route_events(route_used)",
    "CREATE INDEX IF NOT EXISTS idx_document_verification_reports_application_id ON document_verification_reports(application_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviewer_summaries_application_id ON reviewer_summaries(application_id)",
]


def initialize_schema() -> None:
    """Backward-compatible schema initializer used by older entry points."""
    from database.db import init_db

    init_db()
